config/routes.rb
Rails.application.routes.draw do
  # resources :menu
  get 'menu', to: 'menu#index', as: 'menu'
  get 'menu/:item', to: 'menu#show', as: 'menu_item'
  post 'menu/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cafe#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/cafe_controller.rb
class CafeController < ApplicationController
    def index
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  @@menu = { latte: 4.00, scone: 5.00, tea: 3.00 }

  def index
    @menu = MenuItem.all
    # render plain: "Hello"
  end

  def create
    @@menu[params[:name].to_sym] = params[:price]
    redirect_to '/menu'
  end

  def show
    @item = @@menu.find { |k, v| k == params[:item].to_sym }
    if @item.nil?
      render html: "<h5>Item not found!</h5>".html_safe, status: 404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafe_helper.rb
module CafeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/cafe/index.html.erb
<h1>Welcome to Coder Cafe!</h1>

<p>
    <%= link_to "View Menu", menu_path, class: 'foo' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menu/index.html.erb
<h1>Menu</h1>

<table>
  <tr>
    <th>Item</th>
    <th>Price</th>
  </tr>
  <% @menu.each do |item| %>
    <tr>
        <td><%= link_to item.name.capitalize, menu_item_path(item.name) %></td>
        <td><%= "$%.2f" % item.price %></td>
    </tr>
  <% end %>
</table>

app/views/menu/show.html.erb
<h1><%= @item[0].capitalize %></h1>
<h3>$<%= "%.2f" % @item[1] %></h3>